os: osx 
osx_image: xcode10
language: objective-c
before_script: 
  - swiftlint
matrix:
  include:
    - env: NAME=iOS DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - env: NAME=macOS DESTINATION="platform=macOS"
script:
  - xcodebuild test -workspace Peafowl.xcworkspace -scheme Peafowl-${NAME} -destination "${DESTINATION}"
